Repository four-four-four/DAMOA-Frontend, pull requests merged in 2021-12, with the labels that each got.

#21 Feature/user/#19
  package.json
  src/App.vue
  src/components/layout/appbar.vue
  src/components/user/signup/SignUp.vue
  src/components/user/signup/child/EmailSignUp.vue
  src/main.js
  src/router/index.js
  src/util/http-common.js
  src/views/User.vue
Labels: feature, yjs1213, 0xe82de

#23 Feature/user/#19
  src/components/layout/appbar.vue
  src/components/user/signup/SignUp.vue
  src/components/user/signup/child/EmailSignUp.vue
Labels: feature, 0xe82de

#24 Feature/board/#22
  public/img/github.png
  public/img/pic_ah.png
  public/img/pic_js.png
  public/img/pic_ks.png
  public/img/pic_sg.png
  src/App.vue
  src/components/user/notice/Notice.vue
  src/main.js
  src/plugins/vuetify.js
  src/router/index.js
Labels: yjs1213

#26 Feature/user/#20
  package.json
  src/components/layout/appbar.vue
  src/components/user/signin/SignIn.vue
  src/main.js
  src/router/index.js
  src/store/index.js
Labels: feature, 0xe82de
