Repository four-four-four/DAMOA-Frontend, pull requests merged in 2022-02, with the labels that each got.

#34 Refactoring/user/#33
  package-lock.json
  package.json
  src/App.vue
  src/components/layout/appbar.vue
  src/components/layout/footer.vue
  src/components/user/signup/SignUp.vue
  src/components/user/signup/child/EmailSignUp.vue
  src/router/index.js
  src/store/index.js
  src/views/Authors.vue
  src/views/Category.vue
  src/views/Detail.vue
  yarn.lock
Labels: refactoring, 0xe82de

#35 Feature/main/#30
  package-lock.json
  package.json
  src/components/main/trend/Trend.vue
  src/router/index.js
  yarn.lock
Labels: yjs1213

#37 Design/UI/#36
  package-lock.json
  package.json
  public/img/wave-haikei.svg
  src/components/details/sidebar.vue
  src/components/layout/appbar.vue
  src/components/layout/footer.vue
  src/components/user/signin/SignIn.vue
  src/components/user/signup/child/EmailSignUp.vue
  src/main.js
  src/views/Home.vue
  yarn.lock
Labels: yjs1213

#39 Design: #38 - 내비게이션 바의 디자인을 일부 수정하였습니다.
  src/components/layout/appbar.vue
Labels: Design, 0xe82de
